spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: xoUtkarsh
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#    datasource:
#      url: jdbc:h2:mem:test
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: create

server:
  port: 8083
