spring:
  data:
    mongodb:
      connection-string: mongodb://localhost:27017
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: xoUtkarsh
#    password: 123456
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
